---

- name: create user on all servers
  hosts: all
  tasks:
    - name: user creation 
      user:
        name: Ravi
        password: intelliqit
        uid: 1234
        comment: "a Normal user"
        home: /tmp/Ravi
        shell: /bin/bash

...
