---
- name: create directory and copy files into it
  hosts: all
  tasks: 
    - name: create directory
      file:
        name: /tmp/folder1
        state: directory
    - name: copy the password file
      copy:
        src: /etc/passwd
        dest: /tmp/folder1

      
...
