---
- name: install jenkins and required softwares
  hosts: jenkin
  tasks:
    - name: install dependent s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-17-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.479.3/jenkins.war
        dest: /home/ubuntu
- name: configure tomcat and qa and prodserver
  hosts: servers
  tasks:
    - name: install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: copy customized tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
      notify: Restart tomcat
  handlers:
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted

... 
