---
- name: implementing playscope variable
  hosts: all
  vars:  
     - a: tomcat10
     - b: present
     - c: yes
  tasks:
    - name: install/uninstall s/w apps
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

...

