---
- name: configure tomcat10 also tomacat-10 admin
  hosts: all 
  tasks:
    - name: install tomcat10 
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: copy modifies tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port of tomcatfrom 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: pause
      pause:
        minutes: 1
    - name: check tomcat response on server1
      uri:
        url: http://172.31.17.150:9090
        status_code: 200
    - name: check tomcat response on server2
      uri:
        url: http://172.31.31.193:9090 
        status_code: 200

...
      

