---
- name: error handling
  hosts: all
  tasks:
     - block:
        - name: Install git on ubuntu servers using git
          apt:
            name: tree
            state: present
            update_cache: yes
       rescue:
         - name: install git on redhat server using yum
           yum:
             name: tree
             state: present
             update_cache: yes
       always:
         - name: Display success msg 
           debug:
             msg: "git installation done" 
...
